spring:
  data:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: samcomo
    username: root
#    url: jdbc:mariadb://ec2-43-201-206-210.ap-northeast-2.compute.amazonaws.com:3308/samcomo
    url: jdbc:mariadb://172.19.0.2:3308/samcomo
