name: EC2 Test with github actions

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: excuting remote ssh commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USER_NAME}}
        password: ${{secrets.PRIVATE_KEY}}
        script: whoami
        
