name: EC2 Test with github actions

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: excuting remote ssh commands
      run: 
        cd ~/
    - name: pwd
      run : pwd
        
        
